### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by Viiprogrammer** [Viiprogrammer/sms-hub#1]
- [ ] 1. Work on the documentation.
- [ ] 2. Add the secondary address of the api handler for hidden methods to the constructor.
- [ ] 3. Rewrite the current version with a wrapper in promises on request-promise/node-fetch
- [ ] 4. Add more hidden methods
